baseURL = 'https://PandaYip.github.io/'
languageCode = 'en-us'
title = 'Panda Yip 的碎碎念'
theme = "PaperMod"


  [menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2