baseURL = 'https://pandayip.github.io/'
languageCode = 'zh-cn'
title = 'Panda Yip 的碎碎念'
theme = "PaperMod"



  [menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2